version: 0.1
lint:
  definitions:
    - name: test-linter
      files: [ALL]
      commands:
        - name: alpha
          run: "echo alpha"
          output: pass_fail
          success_codes: [0,1]
